@echo off
set SHARED_SPACE_GOOGLE_CLIENT_ID=0
set SHARED_SPACE_GOOGLE_SECRET=0
set SHARED_SPACE_ADMIN_PASSWORD=0
set SHARED_SPACE_SECRET_KEY=0
set SHARED_SPACE_POSTGRES_PASSWORD=0
echo Added Empty Secrets